name: kubernetes-repo-standards

on:
  workflow_call:

jobs:
  kubescore-check:
    uses:
      clubcedille/cedille-workflows/.github/workflows/kube-score-validator.yml@master

  kubeconform-check:
    uses:
      clubcedille/cedille-workflows/.github/workflows/kubeconform.yml@feat/kubeconform-pluto-validation

  deprecated-apis-check:
    uses:
      clubcedille/cedille-workflows/.github/workflows/pluto-deprecated-apis.yml@feat/kubeconform-pluto-validation

  yaml-check:
    uses:
      clubcedille/cedille-workflows/.github/workflows/yaml-lint.yml@master

  terraform-check:
    uses:
      clubcedille/cedille-workflows/.github/workflows/terraform-lint.yml@master
