name: kubernetes-repo-standards

on:
  workflow_call:

jobs:
  kubescore-check:
    uses:
      clubcedille/cedille-workflows/.github/workflows/kube-score.yml@master

  yaml-check:
    uses:
      clubcedille/cedille-workflows/.github/workflows/yaml-lint.yml@alexvegas22-yamllint

  terraform-check:
    uses:
      clubcedille/cedille-workflows/.github/workflows/terraform-lint.yml@master
