name: Markdown lint

on:
  workflow_call:
  push:

jobs:
  markdown-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout default configs
        uses: actions/checkout@v4
        with:
          repository: clubcedille/cedille-workflows
          path: cedille-workflows
          ref: master
          sparse-checkout: |
            .markdownlint.json
            .mlc_config.json
          sparse-checkout-cone-mode: false

      - name: Set config path
        id: config_path
        run: |
          if [ "${{ steps.mlc_check.outputs.found }}" = "true" ]; then
            echo "config_path=${GITHUB_WORKSPACE}/.mlc_config.json" >> $GITHUB_OUTPUT
          else
            echo "config_path=${GITHUB_WORKSPACE}/cedille-workflows/.mlc_config.json" >> $GITHUB_OUTPUT
          fi
        
      - name: Run markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v20
        if: always()
        with:
          globs: '**/*.md'
          config: ${{ github.workspace }}/cedille-workflows/.markdownlint.json
      
      - name: Validating links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: true
          config-file: ${{ steps.config_path.outputs.config_path }}
