name: Terraform lint workflow

on:
  workflow_call:
    inputs:
      config-file-path:
        required: false
        type: string

jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Initialization
        run: terraform init
        continue-on-error: true

      - name: Terraform Format Check
        run: terraform fmt -check -recursive -diff
        continue-on-error: true

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: v0.53.0

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: clubcedille/cedille-workflows
          path: cedille-workflows
          ref: master
          sparse-checkout: |
            .tflint.hcl
          sparse-checkout-cone-mode: false

      - name: Init TFLint
        run: tflint --init

      - name: Check for Terraform files
        id: check_files
        run: |
          if find . -name '*.tf' -not -path './.terraform/*' | grep -q .; then
            echo "has_tf=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_tf=false" >> "$GITHUB_OUTPUT"
            echo "No Terraform files found."
          fi

      - name: Run TFLint
        if: steps.check_files.outputs.has_tf == 'true'
        env:
          CONFIG_FILE_PATH: ${{ github.event.inputs.config-file-path }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          if [ -n "$CONFIG_FILE_PATH" ]; then
            tflint --recursive --config "$WORKSPACE/$CONFIG_FILE_PATH"
          else
            tflint --recursive --config "$WORKSPACE/cedille-workflows/.tflint.hcl"
          fi
