name: Terraform lint workflow

on:
  workflow_call:
    inputs:
      config-file-path:
        required: false
        type: string

jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Initialization
        run: terraform init
        continue-on-error: true

      - name: Terraform Format Check
        run: terraform fmt -check -recursive -diff
        continue-on-error: true

      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: v0.53.0

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: clubcedille/cedille-workflows
          path: cedille-workflows
          ref: master
          sparse-checkout: |
            .tflint.hcl
          sparse-checkout-cone-mode: false

      - name: Init TFLint
        run: tflint --init

      - name: Check for Terraform files
        id: check_files
        run: |
          if [ -z "$(find . -name '*.tf')" ]; then
            echo "No Terraform files found."
            exit 0
          fi

      - name: Run TFLint
        if: steps.check_files.outputs.result == 'true'
        run: |
          if [ -n "${{ github.event.inputs.config-file-path }}" ]; then
            tflint --recursive --config \
            "${{ github.workspace }}/
            ${{ github.event.inputs.config-file-path }}"
          else
            tflint --recursive --config "${{ github.workspace }}/cedille-workflows/.tflint.hcl"
          fi
